version: '3.8'

services:
  # Qdrant векторная база данных
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - vector_network

  # Скрипт загрузки векторов
  vector_loader:
    build: .
    container_name: vector_loader
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./data:/data
    environment:
      - NPY_FILE_PATH=/data/vectors.npy
      - COLLECTION_NAME=vectors
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    networks:
      - vector_network
    restart: "no"  # Запускается только один раз

volumes:
  qdrant_storage:

networks:
  vector_network:
    driver: bridge 